# Generated by Django 4.0.5 on 2022-06-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=300)),
                ('Quantity', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('Name',),
                'index_together': {('id', 'Name')},
            },
        ),
    ]
