# Generated by Django 4.0.5 on 2022-06-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=90)),
                ('Email', models.EmailField(max_length=80)),
                ('Tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QunatityOfProduct', models.IntegerField(null=True)),
                ('Price', models.FloatField(null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Oczekiwanie na płatność', 'Oczekiwanie na płatność'), ('Realizacja', 'Realizacja'), ('W drodze', 'W drodze'), ('Dostarczono', 'dostarczono')], default='Oczekiwanie na płatność', max_length=30)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koszyk.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
